# Generated by Django 3.1.3 on 2020-12-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_location',
            field=models.CharField(choices=[('', 'Shop Location *'), ('sf', 'San Francisco'), ('tahoe', 'Tahoe City'), ('bishop', 'Bishop')], default='sf', max_length=50),
        ),
    ]
