# Generated by Django 3.1.3 on 2020-12-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20201218_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='shop_location',
        ),
    ]
