# Generated by Django 3.1.3 on 2020-12-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_remove_order_shop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shop_location',
            field=models.CharField(choices=[('', 'Shop Location *'), ('sf', 'San Francisco'), ('tahoe', 'Tahoe City'), ('bishop', 'Bishop')], default='', max_length=50),
        ),
    ]
