# Generated by Django 3.1.3 on 2020-12-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_shop_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_cost',
            new_name='discount',
        ),
    ]
